version: '3'

services:
  app:
    build:
      context: ./.docker/PHP/
      dockerfile: Dockerfile
    container_name: microservice-notification
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: microservice-notification-nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

  db:
    build: ./.docker/mysql
    container_name: microservice-notification-db
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
        - "3308:3306"
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
        - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_DATABASE=notifications
        - MYSQL_ROOT_PASSWORD=root
    networks:
        - app-php

networks:
  app-php:
    driver: bridge